name: Singularity Build (docker)
on: 
  push:
    branches:
      - main

jobs:
  build-test-containers:
    runs-on: ubuntu-latest
    strategy:
      # Keep going on other deployments if anything bloops
      fail-fast: false
      matrix:
        singularity_version:
          - '3.9.2'
        program:
          - 'hello_world'

    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    name: Build ${{ matrix.program }}
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v2

      - name: Build container
        env:
          image_name: ${{ matrix.program }}-${{ matrix.version }}-${{ matrix.variant }}
          recipe_name: Singularity.def
        run: |
          echo "Building ${{ matrix.program }}: REF:${GITHUB_REF} SHA:${GITHUB_SHA}"

          echo "IMAGE_NAME=$image_name" >> $GITHUB_ENV
          sudo -E singularity build container.sif "$recipe_name"
          # use latest as tag
          tag="latest"
          # Build the container and name by tag
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Login and deploy container
        if: (github.event_name != 'pull_request')
        env:
          keepgoing: ${{ env.keepgoing }}
        run: |         
          if [[ "${keepgoing}" == "true" ]]; then
             echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
             echo "Pushing $IMAGE_NAME with tag $TAG"
             singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${TAG}
          fi
